# Generated by Django 5.0.2 on 2024-02-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_alter_login_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='login',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='login',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='login',
            name='status',
            field=models.CharField(choices=[('married', 'Married'), ('single', 'Single')], max_length=10),
        ),
    ]
