# Generated by Django 5.0.2 on 2024-02-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_alter_login_age_alter_login_email_alter_login_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('clothing', 'Clothing')], max_length=50),
        ),
    ]
