# Generated by Django 5.0.2 on 2024-02-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Clothing', 'Clothing')], max_length=50),
        ),
    ]
