# Generated by Django 5.0.2 on 2024-02-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_delete_contact_remove_product_subcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
